# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cchen/Documents/software/df_shm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cchen/Documents/software/df_shm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cchen/Documents/software/df_shm/CMakeFiles /home/cchen/Documents/software/df_shm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cchen/Documents/software/df_shm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named df_shm

# Build rule for target.
df_shm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 df_shm
.PHONY : df_shm

# fast build rule for target.
df_shm/fast:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/build
.PHONY : df_shm/fast

#=============================================================================
# Target rules for targets named df_shm-static

# Build rule for target.
df_shm-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 df_shm-static
.PHONY : df_shm-static

# fast build rule for target.
df_shm-static/fast:
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/build
.PHONY : df_shm-static/fast

df_shm.o: df_shm.c.o
.PHONY : df_shm.o

# target to build an object file
df_shm.c.o:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm.c.o
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm.c.o
.PHONY : df_shm.c.o

df_shm.i: df_shm.c.i
.PHONY : df_shm.i

# target to preprocess a source file
df_shm.c.i:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm.c.i
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm.c.i
.PHONY : df_shm.c.i

df_shm.s: df_shm.c.s
.PHONY : df_shm.s

# target to generate assembly for a file
df_shm.c.s:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm.c.s
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm.c.s
.PHONY : df_shm.c.s

df_shm_mmap.o: df_shm_mmap.c.o
.PHONY : df_shm_mmap.o

# target to build an object file
df_shm_mmap.c.o:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_mmap.c.o
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_mmap.c.o
.PHONY : df_shm_mmap.c.o

df_shm_mmap.i: df_shm_mmap.c.i
.PHONY : df_shm_mmap.i

# target to preprocess a source file
df_shm_mmap.c.i:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_mmap.c.i
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_mmap.c.i
.PHONY : df_shm_mmap.c.i

df_shm_mmap.s: df_shm_mmap.c.s
.PHONY : df_shm_mmap.s

# target to generate assembly for a file
df_shm_mmap.c.s:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_mmap.c.s
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_mmap.c.s
.PHONY : df_shm_mmap.c.s

df_shm_posixshm.o: df_shm_posixshm.c.o
.PHONY : df_shm_posixshm.o

# target to build an object file
df_shm_posixshm.c.o:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_posixshm.c.o
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_posixshm.c.o
.PHONY : df_shm_posixshm.c.o

df_shm_posixshm.i: df_shm_posixshm.c.i
.PHONY : df_shm_posixshm.i

# target to preprocess a source file
df_shm_posixshm.c.i:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_posixshm.c.i
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_posixshm.c.i
.PHONY : df_shm_posixshm.c.i

df_shm_posixshm.s: df_shm_posixshm.c.s
.PHONY : df_shm_posixshm.s

# target to generate assembly for a file
df_shm_posixshm.c.s:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_posixshm.c.s
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_posixshm.c.s
.PHONY : df_shm_posixshm.c.s

df_shm_queue.o: df_shm_queue.c.o
.PHONY : df_shm_queue.o

# target to build an object file
df_shm_queue.c.o:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_queue.c.o
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_queue.c.o
.PHONY : df_shm_queue.c.o

df_shm_queue.i: df_shm_queue.c.i
.PHONY : df_shm_queue.i

# target to preprocess a source file
df_shm_queue.c.i:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_queue.c.i
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_queue.c.i
.PHONY : df_shm_queue.c.i

df_shm_queue.s: df_shm_queue.c.s
.PHONY : df_shm_queue.s

# target to generate assembly for a file
df_shm_queue.c.s:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_queue.c.s
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_queue.c.s
.PHONY : df_shm_queue.c.s

df_shm_sysv.o: df_shm_sysv.c.o
.PHONY : df_shm_sysv.o

# target to build an object file
df_shm_sysv.c.o:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_sysv.c.o
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_sysv.c.o
.PHONY : df_shm_sysv.c.o

df_shm_sysv.i: df_shm_sysv.c.i
.PHONY : df_shm_sysv.i

# target to preprocess a source file
df_shm_sysv.c.i:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_sysv.c.i
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_sysv.c.i
.PHONY : df_shm_sysv.c.i

df_shm_sysv.s: df_shm_sysv.c.s
.PHONY : df_shm_sysv.s

# target to generate assembly for a file
df_shm_sysv.c.s:
	$(MAKE) -f CMakeFiles/df_shm.dir/build.make CMakeFiles/df_shm.dir/df_shm_sysv.c.s
	$(MAKE) -f CMakeFiles/df_shm-static.dir/build.make CMakeFiles/df_shm-static.dir/df_shm_sysv.c.s
.PHONY : df_shm_sysv.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... df_shm"
	@echo "... df_shm-static"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... df_shm.o"
	@echo "... df_shm.i"
	@echo "... df_shm.s"
	@echo "... df_shm_mmap.o"
	@echo "... df_shm_mmap.i"
	@echo "... df_shm_mmap.s"
	@echo "... df_shm_posixshm.o"
	@echo "... df_shm_posixshm.i"
	@echo "... df_shm_posixshm.s"
	@echo "... df_shm_queue.o"
	@echo "... df_shm_queue.i"
	@echo "... df_shm_queue.s"
	@echo "... df_shm_sysv.o"
	@echo "... df_shm_sysv.i"
	@echo "... df_shm_sysv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

